spring.application.name=hapi-fhir-demo

# Swagger UI path ? open this in browser after running the app:
# http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

# Makes all endpoints show up in Swagger without extra annotations
springdoc.show-actuator=false